### PR TITLE
Protocol was incorrectly set by red5-client

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
after this fix protocol being used by RTMPS client is 'rtmps'
Unfortunately I got following stacktrace on server while trying to connect:
```
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

[INFO] [http-nio-0.0.0.0-5443-exec-3] org.apache.coyote.http11.Http11NioProcessor - Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
	at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

could you please take a look at this?

**Comment by mondain** [comment]
I can look at it, but are you sure removing the default connection setup is correct?

**Comment by solomax** [comment]
After this fix default connection setup of rtmpclient will be used

**Comment by solomax** [comment]
Hello Paul,

were you able to check RTMPS mode for red5-client?

**Comment by mondain** [comment]
Test out RTMPSClientTest.test31() with your certificate and let me know if its working as expected. Make sure you have mina 2.0.13 or newer.

**Comment by solomax** [comment]
There seems to be lots of issues with 1.0.8-M1 release:

1) red5-parent/pom.xml states mina.version == 2.0.14-SNAPSHOT, there is no downloadable artifacts for mina 2.0.14-SNAPSHOT :(, so my builds are fails

I have downloaded 1.0.8-M1.tgz
2) it contains mina* of version 2.0.12-SNAPSHOT .....
3) it contains spring libraries of version 4.2.4 AND 4.2.6, not sure if it is good idea to mix spring versions ....

can you please check it?
I'll try to test client outside of OM

**Comment by mondain** [comment]
I checked the libs, spring-aop and spring-expression are the only 4.2.4
versions and its odd since we never specify anything less than 4.2.6 for
spring; the server does run ok with the mix. As for mina, i'll change it
back to the range version spec "(2.0.12,2.0.14]" and hopefully that will
find what we need, which would be 2.0.13 for rtmps testing.

**Comment by solomax** [comment]
should I wait for M2 or should I test as is? (with building from sources)

**Comment by mondain** [comment]
It's up-to-you, but you might want to try out the new shutdown process and
possibly the service setup
https://github.com/Red5/red5-service/blob/master/README.md

**Pull request merged**
